

const OpenAI = require('openai-api')
async function generateSummary() {

  const fs = require('fs');
  const path = require('path');


  const openAI = new OpenAI('');
  

  const transcriptFilePath = path.resolve('transcript.txt');
  const transcript = fs.readFileSync(transcriptFilePath, 'utf8');
  
  // while(transcript.length){}
    
    let transcriptFinal = transcript.slice(0,4096);
    console.log(transcriptFinal.length);
    let idx = transcriptFinal.lastIndexOf(".");
    console.log(idx);
    transcriptFinal.slice(idx);
    const length = transcript.length;
    console.log("Number of indices in the text:", length);
    const tokens = transcript.split("");

    const numTokens = tokens.length;

    console.log("Number of tokens in the text:", numTokens);
    

 // Traversing and printing the tokens
//     tokens.forEach((token) => {
//     console.log("Token:", token);
// });


(async () => {
  const completion = await openAI.complete({
    engine: "text-davinci-003",
    prompt: `Please summarize the transcript of the educational video and provide a concise summary in bullet points for easier revision.
    also provide some examples that are being talked about in the video.
    ${transcript}`,
    temperature: 0,
    n: 1,
    max_tokens: 500,
    frequencyPenalty: 0,
    presencePenalty: 0.6,
    stop: [" Human:", " AI:"]
  });

  const { choices } = completion.data;
  console.log(completion.data.choices[0].message);

  let data = `Notes generated by AI :
  ${choices[0].text.trim()}`
  fs.writeFileSync("Summary.txt", data);
})();

}

generateSummary();


